# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
TENSOR_1 = torch.rand(7, 7, dtype=torch.bfloat16)
TENSOR_1, TENSOR_1.shape

(tensor([[0.5391, 0.0586, 0.8633, 0.9219, 0.1055, 0.2031, 0.7305],
         [0.1719, 0.1484, 0.2500, 0.5781, 0.2266, 0.4883, 0.1055],
         [0.2539, 0.2305, 0.0039, 0.7227, 0.9609, 0.0547, 0.1055],
         [0.4023, 0.4336, 0.1875, 0.9727, 0.1719, 0.3750, 0.4844],
         [0.5742, 0.0391, 0.2578, 0.5898, 0.1719, 0.5977, 0.9453],
         [0.0703, 0.1602, 0.3984, 0.7930, 0.7305, 0.7969, 0.2891],
         [0.3789, 0.7344, 0.6641, 0.6992, 0.7773, 0.9727, 0.8789]],
        dtype=torch.bfloat16),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
RANDOM_TENSOR = torch.rand(1, 7, dtype=torch.bfloat16)
# Perform matrix multiplication 
TENSOR_1.matmul(RANDOM_TENSOR.T)

tensor([[1.2891],
        [0.7773],
        [0.9023],
        [1.0938],
        [0.7852],
        [1.2344],
        [1.6328]], dtype=torch.bfloat16)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
RANDOM_TENSOR_1 = torch.rand(7, 7, dtype=torch.bfloat16)
RANDOM_TENSOR_2 = torch.rand(1, 7, dtype=torch.bfloat16)

print(RANDOM_TENSOR_1, "\n", RANDOM_TENSOR_2)

# Matrix multiply tensors
RANDOM_TENSOR_1.matmul(RANDOM_TENSOR_2.T)

tensor([[0.6719, 0.1836, 0.4570, 0.7500, 0.2617, 0.9805, 0.7617],
        [0.4023, 0.0352, 0.8242, 0.0820, 0.9453, 0.1406, 0.3398],
        [0.2734, 0.8438, 0.3438, 0.5469, 0.2266, 0.7539, 0.8984],
        [0.1523, 0.3398, 0.6797, 0.3438, 0.3164, 0.6445, 0.0977],
        [0.3008, 0.2812, 0.0352, 0.5781, 0.4492, 0.8125, 0.9492],
        [0.7695, 0.9922, 0.3086, 0.6836, 0.7500, 0.3203, 0.3867],
        [0.8438, 0.6914, 0.9492, 0.1133, 0.5742, 0.5742, 0.5547]],
       dtype=torch.bfloat16) 
 tensor([[0.6523, 0.1250, 0.7539, 0.0352, 0.7227, 0.4961, 0.1250]],
       dtype=torch.bfloat16)


tensor([[1.6016],
        [1.6875],
        [1.2109],
        [1.2266],
        [1.1250],
        [1.6328],
        [2.1250]], dtype=torch.bfloat16)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

# Create two random tensors on GPU
RANDOM_TENSOR_3 = torch.rand(2, 3, dtype=torch.bfloat16, device=device)
RANDOM_TENSOR_4 = torch.rand(2, 3, dtype=torch.bfloat16, device=device)

print(f"Device: {device}\n{RANDOM_TENSOR_3}\n{RANDOM_TENSOR_4}")

Device: cuda
tensor([[0.1270, 0.8164, 0.5430],
        [0.6602, 0.2715, 0.9727]], device='cuda:0', dtype=torch.bfloat16)
tensor([[0.6211, 0.0276, 0.3262],
        [0.1113, 0.6797, 0.3613]], device='cuda:0', dtype=torch.bfloat16)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
matmul_result = RANDOM_TENSOR_3.matmul(RANDOM_TENSOR_4.T)
matmul_result, matmul_result.shape

(tensor([[0.2793, 0.7656],
         [0.7344, 0.6094]], device='cuda:0', dtype=torch.bfloat16),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
print(matmul_result.max())
# Find min
print(matmul_result.min())

tensor(0.7656, device='cuda:0', dtype=torch.bfloat16)
tensor(0.2793, device='cuda:0', dtype=torch.bfloat16)


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(matmul_result.argmax())

# Find arg min
print(matmul_result.argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
RANDOM_TENSOR_5 = torch.rand(size=(1, 1, 1, 10), dtype=torch.bfloat16, device=device)
print(f"Initial Tensor: \n{RANDOM_TENSOR_5}\n")
# Remove single dimensions
squeezed_tensor = RANDOM_TENSOR_5.squeeze()

# Print out tensors and their shapes
print(f"Squeezed Tensor: \n{squeezed_tensor}\n")

Initial Tensor: 
tensor([[[[0.9531, 0.4941, 0.9414, 0.5938, 0.6992, 0.2090, 0.6758, 0.4805,
           0.6328, 0.5742]]]], device='cuda:0', dtype=torch.bfloat16)

Squeezed Tensor: 
tensor([0.9531, 0.4941, 0.9414, 0.5938, 0.6992, 0.2090, 0.6758, 0.4805, 0.6328,
        0.5742], device='cuda:0', dtype=torch.bfloat16)

